# Generated by Django 3.0.2 on 2020-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('no_of_copies', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'CSE')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
