# Generated by Django 3.0.2 on 2020-03-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrm', '0003_college'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='college',
            new_name='Log',
        ),
    ]
